### ISSUE TITLE
artwork on ios is not displayed MediaSession.setMetadata

### ISSUE THREAD

**Issue by juanico18** [jofr/capacitor-media-session#4]
Testing integration in iOS.
Is not displaying the image correctly:

    artwork: [
      { src: 'https://dummyimage.com/96x96',   sizes: '96x96',   type: 'image/png' },
      { src: 'https://dummyimage.com/128x128', sizes: '128x128', type: 'image/png' },
      { src: 'https://dummyimage.com/192x192', sizes: '192x192', type: 'image/png' },
      { src: 'https://dummyimage.com/256x256', sizes: '256x256', type: 'image/png' },
      { src: 'https://dummyimage.com/384x384', sizes: '384x384', type: 'image/png' },
      { src: 'https://dummyimage.com/512x512', sizes: '512x512', type: 'image/png' },
    ]
    
    I have tested my own images but also with this from the api definition.
    
    The other fields are working well.

**Comment by mariusbolik** [comment]
Hi @juanico18, this is a bug of Webkit: https://bugs.webkit.org/show_bug.cgi?id=247043
Should be fixed in the next iOS Update.

**Comment by juanico18** [comment]
Thanks @mariusbolik I will check once is fixed by apple

**Comment by sanderschnydrig** [comment]
This problem still persists in the latest version of iOS 16.2. No artworks are displayed. Any updates on this? @juanico18 did you manage to get this working?

**Comment by nick-barth** [comment]
Anyone solve this?

**Comment by juanico18** [comment]
@nick-barth we still have that problem.

**Comment by emmernme** [comment]
Doesn't work here either – also looking for a way to serve local images from the app's assets-folder to MediaSession metadata – does anyone have any idea how to do so?

**Comment by mikmikmik** [comment]
For me this is working on iOs and android.
But local image doesn't show up on android, what path do you use? I use /myfile.jpg or ./myfile.jpg both are working on iOs but not on android.

**Comment by Philboisvert** [comment]
@emmernme @juanico18 @nick-barth @sanderschnydrig 

After a lot of researches, the artwork on IOS doesn't work in the simulator regardless if you're on 17.2 or any versions.

This is a Xcode simulator bug and not a MediaSession API bug, if you deploy on your own iPhone instead of the simulator you'll see that the artwork shows up and the Play icon too (which is also not working in the simulator)

@mariusbolik thanks for sharing the thread, saw the solution from recent comments on it 👍 

![image](https://github.com/jofr/capacitor-media-session/assets/45600929/019be324-3854-498b-a511-52a44d8ab724)
